### ISSUE TITLE
Add support for odometry to telemetryDeviceDumper

### ISSUE THREAD

**Issue by drdanz** [robotology/yarp-telemetry#126]
According to @randaz81 the data he would like to dump on the R1 robot is the odometry data coming from the `ILocalization2D` interface.

Data is generated by the `odomLocalizer` device, and is published on the yarp network by `localization2DServer` (now `localization2D_nws_yarp`)

**Comment by Nicogene** [comment]
The structure of `OdometryData` is:
```c++
double odom_x;


double odom_y;


double odom_theta;


double base_vel_x;


double base_vel_y;


double base_vel_theta;


double odom_vel_x;


double odom_vel_y;
```

We can encode this in 2 ways:
- 1 channel of size 8
- 8 separated channels of size 1

I personally prefer the first solution, because to the 8 channels you have to add also the others if enabled and may mess up the structure of the mat file.

What do you think about it @randaz81 @drdanz @AlexAntn @traversaro ?

**Comment by randaz81** [comment]
I am also for the first solution.

From the logic point of view, another possible solution would be to have three channels, each of them consisting of three values inside (if you notice, three values are positions, three values are velocities, three values are velocities in a different coordinate frame). But I don't know if it is feasible, so the first solution is ok.
